### ISSUE TITLE
Fish number never increases

### ISSUE THREAD

**Issue by erolm-a** [resistance-modelling/slim#102]
My guess is that we could use a logistic function fitted onto the 2016 Scottish survey or the FAO data. The old `surv.py` file apparently did serve this purpose.

**Comment by anthonyohare** [comment]
I don't think the cages are in use long enough for fish to breed and I don't think it's possible so we can ignore it here and allow the fish numbers to decrease. Cages are just stocked and the fish allowed to grow/fatten up until harvest.

**Comment by erolm-a** [comment]
Alright then, we can close this for now.
