### ISSUE TITLE
Tidy up unused items

### ISSUE THREAD

**Issue by anthonyohare** [resistance-modelling/slim#105]
Tau leaping was removed from the code but there is a reference to the tau-step in the params.json file which needs to be removed.

The resistanceBVs.txt file is created by a simulation but is empty. It is not clear what it should contain but all output is contained in the output file so we should remove this resistanceBVs.txt file.

**Comment by anthonyohare** [comment]
Not sure how to link to src or highlight but it's in slim/refactor/config_data/Fyne/params.json line 10-13
    "tau": {
        "description": "Tau value for tau-leaping",
        "value": 1
    },

**Comment by erolm-a** [comment]
I believe that has already been removed in the current PR, but I'll be sure to link this as well.

-------- Original Message --------
