### ISSUE TITLE
Linting and typing

### ISSUE THREAD

**Issue by erolm-a** [resistance-modelling/slim#14]
I see this code already uses pylint, which is good. But I think it would be nice to introduce type hints just to make my IDE (and also our testing) life a bit easier.

Type errors are a notoriously bad source of bugs of all kinds in python and type hints may give a hand. Unfortunately in my experience pylint does a poor job at type inference and leads to quite verbose code so you may prefer mypy.

This is an open-ended discussion issue, feel free to propose better solutions.

**Comment by anthonyohare** [comment]
I've no experience of my pay but agree with you on pylint. I'd be happy to see other code checkers/validates used as well as or instead of pylint.

**Comment by erolm-a** [comment]
we decided to take a hybrid approach when it comes to typing:

- lenient typing will be carried out by pytype. As a plus, this generates exportable type information for further annotation. Might be worth looking into if we ever want to use documentation generators.
- longwinded, unforgiving typing is carried out by mypy. Note that mypy is not simply more "complete" than pytype: there are a class of errors that can be caught by pytype but not by mypy and vice-versa.
