### ISSUE TITLE
Infection variance and mating calculation have linear complexity on the population

### ISSUE THREAD

**Issue by erolm-a** [resistance-modelling/slim#153]
This causes strong repercussions to the runtime once a pandemic soars.

**Comment by anthonyohare** [comment]
This is to be expected as the number of calculations soars with a growing epidemic (more transmission routes or be calculated). 
We can profile this (hopefully).

**Comment by erolm-a** [comment]
Another function with bad time complexity is `get_lice_treatment_mortality`. The algorithm used [here](https://github.com/resistance-modelling/slim/blob/36842c864e777649b10b8c164ca2d4a6a07901c7/refactor/src/Cage.py#L278) is linear in the number of dead lice - and numpy's sampling functions are not too fast. Luckily, after [the last commit](https://github.com/resistance-modelling/slim/commit/36842c864e777649b10b8c164ca2d4a6a07901c7#diff-5578ff261866fb351fa73e5be18fcdb46cb54c3bda6a7cb2c1dc03f7c4a7c34d) the issue is not as critical but I'd expect a similar replacement with a multinomial to do marvels.
