### ISSUE TITLE
Introduction document

### ISSUE THREAD

**Issue by magicicada** [resistance-modelling/slim#184]
- In “What will be our loss if we apply treatment as soon as the AF aggregation ratio reaches x?” What does ‘AF’ mean? Preferably remove acronym or define.

**Comment by erolm-a** [comment]
Oh, Adult Females or L5f. That's the jargon typically used in papers. I don't object to expanding the acronym.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
