### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by erolm-a** [resistance-modelling/slim#22]
Pinned issue, it will act as a placeholder to reference commit to.

Currently tested:
- [x] Farm
- [x] Cage/Reservoir
  - [x] Development rate
  - [x] Mating phase
  - [X] Egg production
  - [X] Fish background and lice-induced mortality
  - [X] Infection
  - [x] Delta update
  - [x] Offspring and hatching
  - [x] Lice mortality update
     - [X] background mortality update
     - [x] treatment mortality update
     - [ ] cleaner fish mortality update (?) (see #26 )

Furthermore, it would be interesting to add some coverage testing - possibly generate a report via the CI and a fancy badge.

**Comment by erolm-a** [comment]
@SaraJakubiak would you mind writing a few tests for the reservoir when you've got some time?

**Comment by erolm-a** [comment]
@magicicada could you write a few tests while you are working on your branch? Also, since you are taking ova into account you should likely change the expected outputs for the update function.

**Comment by magicicada** [comment]
@erolm-a Sure!  I don't have a ton of experience in dealing with the style of tests that we're using, but I'm happy to learn.  Will go have a look at what's there now, and learn from that.

**Comment by magicicada** [comment]
@erolm-a OK, super-naive git question.  My mating branch is from before the testing class for Cage existed.    Obviously, I want to add my tests in there - what's the best way to deal with this?

**Comment by erolm-a** [comment]
git checkout to master, pull, re-checkout to your branch, merge locally with master, fix the merge conflicts and push another commit to this branch.

**Comment by magicicada** [comment]
An exciting new git endeavour for me.  I shall try, and cry for help if I get myself in a 'gituation'.

**Comment by erolm-a** [comment]
Alternatively, one could perform a rebase of the first commit but I find it dangerous and likely impossible. Rebases are arcane magic to me.
