### ISSUE TITLE
On SIMD and directions of refactoring

### ISSUE THREAD

**Issue by erolm-a** [resistance-modelling/slim#32]
In a number of occasions it may be required for `Cage`s to interact with each other. A few examples:

- CH/PA/A growth equations (according to Aldrin) involves a nested sum of different cages. This is worsened when fish removal is taken into account (see the paper's supplementary material). Personally, I do not fully understand why interaction is needed for PA and A stages but it is reasonable when it comes to CH as the lice are mobile and may float across cage nets in the real world.
- infection rates for the CH stage
- flynn networks and in general any matrix/graph-looking operation

The current OOP approach can definitely work but has a few issues:

- it requires computation to be redone (e.g. iterating and summating over the same value over and over)
- when memoizing, move more complexity onto the farmer class, causing issues when separating concerns
- definitely not SIMD-optimisable. Example: the equation for the new development rates in section 2.2.5 is [currently (and erroneously - softmaxing is missing) implemented](https://github.com/magicicada/slim/blob/51aaec9e149b9502fee56e1c5e5398d0248d8e8d/refactor/src/Cage.py#L327) as a manual list iteration with sum. If all the d_CO_c values were stored in the same pool then the computation would trivially be:

```python
d_CO = np.exp(eta_CO)/(1 + np.sum(np.exp(eta_CO))
```
this is nice to read, has O(c) complexity compared to calculating the sum inside every cage (O(c^2)) and much easier to vectorise. This is especially relevant if we decide to switch to jax or similar frameworks.

So we need to investigate whether keeping all those values within the Cage class is a good idea or whether we should make almost-global vector pools and put them inside Farm. I know this may make people frown as it may sound like a big step back - and it heavily depends on how effective micro-optimisations are at this stage.

**Comment by magicicada** [comment]
A few questions: what are flynn networks and SIMD here, please?

**Comment by erolm-a** [comment]
> what are flynn networks

a typo. I meant Linnhe networks

> SIMD

"single instruction, multiple data", i.e. instructions that perform the same operation to vectors of data. By metonymy, I referred to high-level numpy instruction (e.g. `np.sum()` rather than `sum([x for x in some_list]`) as they are optimized with low-level SIMD instructions.

**Comment by magicicada** [comment]
Model complexity has grown - closing this issue for now.
