### ISSUE TITLE
Add parameter sources to JSON files

### ISSUE THREAD

**Issue by SaraJakubiak** [resistance-modelling/slim#64]
At the moment the sources of data are both in `README.md` and descriptions of JSON configuration files. 

The aim of this issue is to move the sources of constants into the JSON files so that the general structure of the JSON is as follows:

`{"name":  { "description": "dummy variable", "source": "Dummy et al", "value": 0}}`

The keys could also include `"notes"` when the source requires further explanation.

**Comment by erolm-a** [comment]
Because of #139 this would require a modification in the schema, which in turn would require a non-standard property. We believe just a comment beyond the description is enough for now.
