### ISSUE TITLE
Farm and cage start days

### ISSUE THREAD

**Issue by SaraJakubiak** [resistance-modelling/slim#72]
At the moment the code does not take into account the start dates of farms and cages. 

Cages that have not started yet should not be taken into consideration for cage updates - since we assume it has not been populated with fish yet (so no treatment, fish mortality, lice progression dependent on fish, etc).

However, farms that have not started should still be available for interfarm travel as the farm might start operating before the eggs from different, already operating farm arrive at it.

**Comment by magicicada** [comment]
Plan for lice moving to a cage before the cage date: model only the lice progression, but nothing with the fish.
