### ISSUE TITLE
Interfarm travel probabilities 

### ISSUE THREAD

**Issue by SaraJakubiak** [resistance-modelling/slim#76]
Update the interfarm probabilities with actual values. At the moment the interfarm movement assumes equal probability of travel between all farms. 

The original code used `refactor/config_data/Fyne/interfarm_prob.csv` to calculate the egg flow between the farms but the number are not probabilities but rates - needs further investigation.

**Comment by magicicada** [comment]
These came from Thomas Adam at UHI - I believe they include survival rates.
